# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WorkspaceMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WorkspaceMobile
  rn_path = '../node_modules/react-native'
  pod 'Mixpanel'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-onesignal',
  :path => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
  :inhibit_warnings => true

  target 'WorkspaceMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'WorkspaceMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WorkspaceMobile-tvOS

  target 'WorkspaceMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|

    if target.name == "React"
      target.remove_from_project
    end
    
    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
