export default {
  title: {},
  header1: {},
  header1Light: {},
  header1Scrolled: {},
  header2: {},
  header3: {},
  header3Light: {},
  header3White: {},
  captionDark: {},
  captionLight: {},
  captionGreen: {},
  label: {},
  labelGreen: {},
  labelRed: {},
  body: {},
  bodyBold: {},
  bodySubtitle: {},
  bodyBoldWhite: {},
};
