export default {
  title: {
    _fontFamily: 'regular',
    fontSize: 43,
    lineHeight: 55,
    letterSpacing: -1,
    color: '$dark',
  },
  header1: {
    _fontFamily: 'bold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -1.2,
    color: '$dark',
  },
  header1Light: {
    _fontFamily: 'bold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -1.2,
    color: '$sw3',
  },
  header1Scrolled: {
    _fontFamily: 'bold',
    fontSize: 18,
    lineHeight: 36,
    letterSpacing: -0.72,
    color: '$dark',
  },
  header2: {
    _fontFamily: 'medium',
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: -0.34,
    color: '$dark',
  },
  header3: {
    _fontFamily: 'regular',
    fontSize: 16,
    lineHeight: 18,
    color: '$dark',
  },
  header3ForInputs: {
    _fontFamily: 'regular',
    fontSize: 16,
    color: '$dark',
  },
  header3Light: {
    _fontFamily: 'regular',
    fontSize: 16,
    lineHeight: 18,
    color: '$sw3',
  },
  header3White: {
    _fontFamily: 'regular',
    fontSize: 16,
    lineHeight: 18,
    color: '$base',
  },
  captionDark: {
    _fontFamily: 'medium',
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.78,
    color: '$dark',
  },
  captionLight: {
    _fontFamily: 'medium',
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.78,
    color: '$sw3',
  },
  captionGreen: {
    _fontFamily: 'medium',
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.78,
    color: '$green',
  },
  labelLight: {
    _fontFamily: 'medium',
    fontSize: 11,
    lineHeight: 23,
    letterSpacing: 0.3,
    color: '$sw3',
  },
  labelGreen: {
    _fontFamily: 'medium',
    fontSize: 11,
    lineHeight: 23,
    letterSpacing: 0.3,
    color: '$green',
  },
  labelRed: {
    _fontFamily: 'medium',
    fontSize: 11,
    lineHeight: 23,
    letterSpacing: 0.3,
    color: '$red',
  },
  bodyDark: {
    _fontFamily: 'regular',
    fontSize: 14,
    lineHeight: 18,
    color: '$dark',
  },
  bodyDarkForInputs: {
    _fontFamily: 'regular',
    fontSize: 14,
    color: '$dark',
  },
  bodyBold: {
    _fontFamily: 'medium',
    fontSize: 14,
    lineHeight: 18,
    color: '$dark',
  },
  bodyLight: {
    _fontFamily: 'regular',
    fontSize: 14,
    lineHeight: 18,
    color: '$sw3',
  },
  bodyWhite: {
    _fontFamily: 'medium',
    fontSize: 14,
    lineHeight: 18,
    color: '$base',
  },
};
